# Generated by Django 3.1 on 2020-08-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_auto_20200808_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
    ]
