# Generated by Django 3.1 on 2020-08-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developpers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developper',
            name='prefered_language',
            field=models.CharField(default='Python', max_length=255, null=True),
        ),
    ]
