# Generated by Django 3.1 on 2020-08-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developpers', '0002_auto_20200808_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developper',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='developper',
            name='prefered_language',
            field=models.CharField(blank=True, default='Python', max_length=255, null=True),
        ),
    ]
